version: "3.9"

services:
  mariadb:
    image: mariadb:11.4
    container_name: my_mariadb_test
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3325:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
