name: cspell

on: push

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install CSpell
        run: npm install -g cspell@latest
      - name: Check spelling
        run: npx cspell "**" --no-progress --config .cspell.json
