name: prettier

on: push

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install Prettier
        run: npm install --save-dev --save-exact prettier
      - name: Run Prettier check
        run: npx prettier . --check
